# Generated by Django 4.1.7 on 2023-02-20 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HousePlants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_plant', models.CharField(max_length=50)),
                ('leaf_color', models.CharField(choices=[('WH', 'White'), ('BL', 'Blue'), ('YE', 'Yellow'), ('GR', 'Green'), ('PU', 'Purple'), ('OR', 'Orange'), ('MO', 'Mottled'), ('PI', 'Pink'), ('DA', 'Dark_blue'), ('RE', 'Red'), ('B', 'Black')], max_length=2)),
                ('level_of_care', models.CharField(choices=[('S', 'Не нуждается в особых требованиях для роста и цветения'), ('M', 'В целом неприхотливо, может предъявлять особые для данного вида требования'), ('L', 'Требовательно в уходе')], max_length=1)),
                ('irrigation_level', models.CharField(choices=[('S', 'Засухоустойчиво'), ('M', 'Обильный полив 2-3 раза в неделю'), ('L', 'Нуждается в постоянно увлажненной почве (полив более 3-х раз в неделю)')], max_length=1)),
                ('light_level', models.CharField(choices=[('S', 'Теневыносливо'), ('M', 'Допустимы прямые лучи несколько часов, восточная, западная ориентация'), ('L', 'Западная, южная ориентация, может потребовать несколько часов прямых солнечных лучей')], max_length=1)),
                ('feeding', models.CharField(choices=[('S', 'Достаточно питательных веществ из собственной почвы или редкого удобрения'), ('M', 'Удобрение только в период активного роста'), ('L', 'Требует частого удобрения (в том числе круглый год)')], max_length=1)),
                ('humidity', models.CharField(choices=[('S', 'Нетребовательно к влажности воздуха'), ('M', 'Умеренная влажность (не менее 35%, обычная уличная влажность воздуха в тени'), ('L', 'Высокая влажность (60% и более: тропики круглый год; типичная влажность летом в средней полосе)')], max_length=1)),
                ('temp', models.CharField(choices=[('5', 'холодное содержание (+5 — +18°C)'), ('18', 'умеренно-теплое содержание (+18 — +25°C)'), ('22', 'теплое содержание (+22 — +27°C)'), ('-', 'отсутствует')], max_length=2)),
                ('min_height', models.PositiveIntegerField()),
                ('max_height', models.PositiveIntegerField()),
                ('pic_of_plant', models.ImageField(upload_to='')),
                ('content_or_description', models.TextField()),
                ('flowering_time', models.CharField(max_length=100)),
                ('soil', models.CharField(max_length=100)),
            ],
        ),
    ]
