# Generated by Django 4.1.7 on 2023-03-06 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='houseplants',
            old_name='temp',
            new_name='temperature',
        ),
        migrations.AddField(
            model_name='houseplants',
            name='homeland',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='houseplants',
            name='flowering_time',
            field=models.CharField(max_length=50),
        ),
    ]
