# Generated by Django 4.1.7 on 2023-04-07 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0004_alter_houseplants_feeding_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houseplants',
            name='feeding',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='houseplants',
            name='humidity',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='houseplants',
            name='irrigation_level',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='houseplants',
            name='level_of_care',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='houseplants',
            name='temperature',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
