# Generated by Django 4.1.7 on 2023-04-14 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0005_alter_houseplants_feeding_alter_houseplants_humidity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houseplants',
            name='flowering_time',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='houseplants',
            name='leaf_color',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='houseplants',
            name='light_level',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='houseplants',
            name='soil',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
