# Generated by Django 4.1.7 on 2023-04-14 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0007_alter_houseplants_name_of_plant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houseplants',
            name='name_of_plant',
            field=models.CharField(max_length=250),
        ),
    ]
