# Generated by Django 4.1.7 on 2023-04-14 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0008_alter_houseplants_name_of_plant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houseplants',
            name='feeding',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='houseplants',
            name='flowering_time',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='houseplants',
            name='homeland',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='houseplants',
            name='humidity',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='houseplants',
            name='irrigation_level',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='houseplants',
            name='leaf_color',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='houseplants',
            name='level_of_care',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='houseplants',
            name='light_level',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='houseplants',
            name='name_of_plant',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='houseplants',
            name='soil',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='houseplants',
            name='temperature',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
