# Generated by Django 4.1.7 on 2023-04-14 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0009_alter_houseplants_feeding_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houseplants',
            name='content_or_description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='houseplants',
            name='max_height',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='houseplants',
            name='min_height',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='houseplants',
            name='pic_of_plant',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
