# Generated by Django 4.1.7 on 2023-05-11 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0010_alter_houseplants_content_or_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='houseplants',
            name='copy',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
