# Generated by Django 4.1.7 on 2023-05-11 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0011_houseplants_copy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='houseplants',
            old_name='copy',
            new_name='copy_pic',
        ),
    ]
