# Generated by Django 4.1.7 on 2023-05-11 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0012_rename_copy_houseplants_copy_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houseplants',
            name='copy_pic',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
