# Generated by Django 4.1.7 on 2023-05-12 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0013_alter_houseplants_copy_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='houseplants',
            name='copy_pic',
        ),
        migrations.AlterField(
            model_name='houseplants',
            name='pic_of_plant',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
