# Generated by Django 4.1.7 on 2023-05-12 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0014_remove_houseplants_copy_pic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='houseplants',
            name='short_name',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
